import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { Pixelify_Sans } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const pixelify = Pixelify_Sans({
  subsets: ["latin"],
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader />

        <header className="border-b-4 border-black flex justify-between p-6 items-center bg-white selection:bg-red-500https://github.com/SaukiFutaki">
          <Link href="/">
            <p className={`${pixelify.className} md:text-5xl text-black`}>Anime</p>
          </Link>
        </header>

        <div className="">{children}</div>
      </body>
    </html>
  );
}
